from __future__ import annotations

from soundcalc.zkvms.fri_based_vm import FRIBasedCircuit, FRIBasedVM, FRIBasedVMConfig

from ..common.fields import *

from pathlib import Path
import yaml

### Load ZisK configuration from YAML file
### It can be autogenerated by doing the following:
###  1. Download pil2-proofman (https://github.com/0xPolygonHermez/pil2-proofman.git) and connect it to feature/soundness-info branch
###  2. Download the current zisk setup. Currently, it is preferrable to download it from source since using ziskup will automatically generate the extended fixed polynomials, which are not required. It uses around 7GB. It can be downloaded from "https://storage.googleapis.com/zisk-setup/zisk-provingkey-0.14.0.tar.gz". It can be extracted with "tar -xvzf zisk-provingkey-0.14.0.tar.gz"
###  3. Run the following command on pil2-proofman: "cargo run --bin proofman-cli soundness -k <setup> -a -o <yaml>"
yaml_path = Path(__file__).parent / "zisk.yml"

with open(yaml_path, "r") as f:
    config = yaml.safe_load(f)


def _make_circuit(name: str, type: str, section: dict) -> FRIBasedCircuit:
    FRI_folding_factors = [1 << (section["fri_fa"][i] - section["fri_fa"][i + 1]) for i in range(len(section["fri_fa"]) - 1)]
    FRI_early_stop_degree = 1 << section["fri_fa"][-1]

    cfg = FRIBasedVMConfig(
        name=f"{name}-{type}" if type is not None else name,
        hash_size_bits=256,
        rho=1 / (1 << section["blowup_factor"]),
        trace_length=1 << section["n_bits"],
        field=GOLDILOCKS_3,
        num_columns=section["witness"] + section["fixed"],
        batch_size=section["pols"],
        power_batching=True,
        num_queries=section["queries"],
        AIR_max_degree=section["d"],
        FRI_folding_factors=FRI_folding_factors,
        FRI_early_stop_degree=FRI_early_stop_degree,
        max_combo=section["opening_points"],
        grinding_query_phase=section.get("grinding_query_phase", 0),
    )

    return FRIBasedCircuit(cfg)

class ZiskPreset:
    @staticmethod
    def default() -> FRIBasedVM:
        """
        Create a ZisK VM with multiple circuits.

        For ZisK, we populate the parameters from the following data:
        https://github.com/ethereum/soundcalc/issues/18
        """

        circuits = []

        ### Basics AIRs configuration
        for name, section in config.get("basics").items():
            circuits.append(_make_circuit(name, None, section))

        ### Compressor AIRs configuration
        for name, section in config.get("compressor").items():
            circuits.append(_make_circuit(name, "compressor", section))

        ### Recursive2 AIRs configuration
        for name, section in config.get("recursive2").items():
            circuits.append(_make_circuit(name, None, section))

        ### VADCOP final AIR configuration
        circuits.append(_make_circuit("vadcop_final", None, config.get("vadcop_final", None)))

        return FRIBasedVM(name="ZisK", circuits=circuits)
